/* Generated by Yosys 0.62+9 (git sha1 1717fa018, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module \$paramod\operand_gating\DATA_WIDTH=s32'00000000000000000000000000001000 (activation, weight, mac_enable);
  input [7:0] activation;
  wire [7:0] activation;
  input [7:0] weight;
  wire [7:0] weight;
  output mac_enable;
  wire mac_enable;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  sky130_fd_sc_hd__nor4_1 _05_ (
    .A(activation[7]),
    .B(activation[4]),
    .C(activation[2]),
    .D(activation[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor4_1 _06_ (
    .A(activation[6]),
    .B(activation[5]),
    .C(activation[3]),
    .D(activation[0]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__or4_1 _07_ (
    .A(weight[2]),
    .B(weight[3]),
    .C(weight[0]),
    .D(weight[1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__or4_1 _08_ (
    .A(weight[6]),
    .B(weight[7]),
    .C(weight[4]),
    .D(weight[5]),
    .X(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _09_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _10_ (
    .A1(_00_),
    .A2(_01_),
    .B1(_04_),
    .Y(mac_enable)
  );
endmodule

module processing_element(clk, rst_n, pe_enable, activation_in, weight_in, psum_in, valid_in, activation_out, weight_out, psum_out, valid_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input pe_enable;
  wire pe_enable;
  input [7:0] activation_in;
  wire [7:0] activation_in;
  input [7:0] weight_in;
  wire [7:0] weight_in;
  input [31:0] psum_in;
  wire [31:0] psum_in;
  input valid_in;
  wire valid_in;
  output [7:0] activation_out;
  wire [7:0] activation_out;
  output [7:0] weight_out;
  wire [7:0] weight_out;
  output [31:0] psum_out;
  wire [31:0] psum_out;
  output valid_out;
  wire valid_out;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire mac_enable;
  sky130_fd_sc_hd__clkinv_1 _0560_ (
    .A(valid_out),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__mux2_1 _0561_ (
    .A0(weight_out[6]),
    .A1(weight_in[6]),
    .S(pe_enable),
    .X(_0000_)
  );
  sky130_fd_sc_hd__mux2_1 _0562_ (
    .A0(weight_out[5]),
    .A1(weight_in[5]),
    .S(pe_enable),
    .X(_0001_)
  );
  sky130_fd_sc_hd__mux2_1 _0563_ (
    .A0(weight_out[4]),
    .A1(weight_in[4]),
    .S(pe_enable),
    .X(_0002_)
  );
  sky130_fd_sc_hd__mux2_1 _0564_ (
    .A0(weight_out[3]),
    .A1(weight_in[3]),
    .S(pe_enable),
    .X(_0003_)
  );
  sky130_fd_sc_hd__mux2_1 _0565_ (
    .A0(weight_out[2]),
    .A1(weight_in[2]),
    .S(pe_enable),
    .X(_0004_)
  );
  sky130_fd_sc_hd__mux2_1 _0566_ (
    .A0(weight_out[1]),
    .A1(weight_in[1]),
    .S(pe_enable),
    .X(_0005_)
  );
  sky130_fd_sc_hd__mux2_1 _0567_ (
    .A0(weight_out[0]),
    .A1(weight_in[0]),
    .S(pe_enable),
    .X(_0006_)
  );
  sky130_fd_sc_hd__and2_0 _0568_ (
    .A(pe_enable),
    .B(valid_in),
    .X(_0050_)
  );
  sky130_fd_sc_hd__nand2_1 _0569_ (
    .A(pe_enable),
    .B(valid_in),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__nand2b_1 _0570_ (
    .A_N(activation_in[3]),
    .B(weight_in[7]),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__nand2_1 _0571_ (
    .A(activation_in[4]),
    .B(weight_in[6]),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__nand2_1 _0572_ (
    .A(activation_in[5]),
    .B(weight_in[5]),
    .Y(_0054_)
  );
  sky130_fd_sc_hd__xor2_1 _0573_ (
    .A(_0052_),
    .B(_0053_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__maj3_1 _0574_ (
    .A(_0052_),
    .B(_0053_),
    .C(_0054_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__nand2_1 _0575_ (
    .A(activation_in[6]),
    .B(weight_in[5]),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__nand2b_1 _0576_ (
    .A_N(activation_in[4]),
    .B(weight_in[7]),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__nand2_1 _0577_ (
    .A(activation_in[5]),
    .B(weight_in[6]),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__xnor2_1 _0578_ (
    .A(_0058_),
    .B(_0059_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__xor2_1 _0579_ (
    .A(_0057_),
    .B(_0060_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0580_ (
    .A(_0061_),
    .SLEEP(_0056_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__nand2_1 _0581_ (
    .A(activation_in[7]),
    .B(weight_in[2]),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__nand2_1 _0582_ (
    .A(activation_in[7]),
    .B(weight_in[3]),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__nand3_1 _0583_ (
    .A(activation_in[7]),
    .B(weight_in[3]),
    .C(weight_in[4]),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__o21ai_0 _0584_ (
    .A1(weight_in[3]),
    .A2(weight_in[4]),
    .B1(activation_in[7]),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0585_ (
    .A(_0065_),
    .SLEEP(_0066_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__nand3_1 _0586_ (
    .A(activation_in[7]),
    .B(weight_in[2]),
    .C(_0067_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__xnor2_1 _0587_ (
    .A(_0063_),
    .B(_0067_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__xor2_1 _0588_ (
    .A(_0063_),
    .B(_0067_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__xnor2_1 _0589_ (
    .A(_0056_),
    .B(_0061_),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__a21oi_1 _0590_ (
    .A1(_0069_),
    .A2(_0071_),
    .B1(_0062_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__maj3_1 _0591_ (
    .A(_0057_),
    .B(_0058_),
    .C(_0059_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__nand2_1 _0592_ (
    .A(activation_in[7]),
    .B(weight_in[5]),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__nand2b_1 _0593_ (
    .A_N(activation_in[5]),
    .B(weight_in[7]),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__nand2_1 _0594_ (
    .A(activation_in[6]),
    .B(weight_in[6]),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__xnor2_1 _0595_ (
    .A(_0075_),
    .B(_0076_),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__xnor2_1 _0596_ (
    .A(_0074_),
    .B(_0077_),
    .Y(_0078_)
  );
  sky130_fd_sc_hd__nor2_1 _0597_ (
    .A(_0073_),
    .B(_0078_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__xor2_1 _0598_ (
    .A(_0073_),
    .B(_0078_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__xnor2_1 _0599_ (
    .A(_0069_),
    .B(_0080_),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__nor2_1 _0600_ (
    .A(_0072_),
    .B(_0081_),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__and2_0 _0601_ (
    .A(activation_in[7]),
    .B(weight_in[0]),
    .X(_0083_)
  );
  sky130_fd_sc_hd__o21ai_0 _0602_ (
    .A1(weight_in[0]),
    .A2(weight_in[1]),
    .B1(activation_in[7]),
    .Y(_0084_)
  );
  sky130_fd_sc_hd__a21o_1 _0603_ (
    .A1(_0065_),
    .A2(_0068_),
    .B1(_0084_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__clkinv_1 _0604_ (
    .A(_0085_),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__nand3_1 _0605_ (
    .A(_0065_),
    .B(_0068_),
    .C(_0084_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__and2_0 _0606_ (
    .A(_0085_),
    .B(_0087_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__nand2_1 _0607_ (
    .A(_0085_),
    .B(_0087_),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__xor2_1 _0608_ (
    .A(_0072_),
    .B(_0081_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__a21oi_1 _0609_ (
    .A1(_0088_),
    .A2(_0090_),
    .B1(_0082_),
    .Y(_0091_)
  );
  sky130_fd_sc_hd__a21oi_1 _0610_ (
    .A1(_0069_),
    .A2(_0080_),
    .B1(_0079_),
    .Y(_0092_)
  );
  sky130_fd_sc_hd__maj3_1 _0611_ (
    .A(_0074_),
    .B(_0075_),
    .C(_0076_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__nand2_1 _0612_ (
    .A(activation_in[7]),
    .B(weight_in[6]),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__nand2b_1 _0613_ (
    .A_N(activation_in[6]),
    .B(weight_in[7]),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__xor3_1 _0614_ (
    .A(_0074_),
    .B(_0094_),
    .C(_0095_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__nor2_1 _0615_ (
    .A(_0093_),
    .B(_0096_),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__xor2_1 _0616_ (
    .A(_0093_),
    .B(_0096_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__xnor2_1 _0617_ (
    .A(_0069_),
    .B(_0098_),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__nor2_1 _0618_ (
    .A(_0092_),
    .B(_0099_),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__xor2_1 _0619_ (
    .A(_0092_),
    .B(_0099_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__xnor2_1 _0620_ (
    .A(_0088_),
    .B(_0101_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__xnor2_1 _0621_ (
    .A(_0091_),
    .B(_0102_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__maj3_1 _0622_ (
    .A(_0085_),
    .B(_0091_),
    .C(_0102_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__a21oi_1 _0623_ (
    .A1(_0088_),
    .A2(_0101_),
    .B1(_0100_),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__a21oi_1 _0624_ (
    .A1(_0069_),
    .A2(_0098_),
    .B1(_0097_),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__nand2b_1 _0625_ (
    .A_N(activation_in[7]),
    .B(weight_in[7]),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__maj3_1 _0626_ (
    .A(_0074_),
    .B(_0094_),
    .C(_0095_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__a31oi_1 _0627_ (
    .A1(activation_in[7]),
    .A2(weight_in[5]),
    .A3(weight_in[6]),
    .B1(_0108_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__a31o_1 _0628_ (
    .A1(_0074_),
    .A2(_0094_),
    .A3(_0107_),
    .B1(_0109_),
    .X(_0110_)
  );
  sky130_fd_sc_hd__nand2_1 _0629_ (
    .A(_0070_),
    .B(_0110_),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__xnor2_1 _0630_ (
    .A(_0070_),
    .B(_0110_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__nor2_1 _0631_ (
    .A(_0106_),
    .B(_0112_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__xor2_1 _0632_ (
    .A(_0106_),
    .B(_0112_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__xnor2_1 _0633_ (
    .A(_0088_),
    .B(_0114_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__nor2_1 _0634_ (
    .A(_0105_),
    .B(_0115_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__xor2_1 _0635_ (
    .A(_0105_),
    .B(_0115_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__xnor2_1 _0636_ (
    .A(_0086_),
    .B(_0117_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__nor2_1 _0637_ (
    .A(_0104_),
    .B(_0118_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__xor2_1 _0638_ (
    .A(_0104_),
    .B(_0118_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__nand2b_1 _0639_ (
    .A_N(activation_in[2]),
    .B(weight_in[7]),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__nand2_1 _0640_ (
    .A(activation_in[3]),
    .B(weight_in[6]),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__nand2_1 _0641_ (
    .A(activation_in[4]),
    .B(weight_in[5]),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__xnor2_1 _0642_ (
    .A(_0121_),
    .B(_0122_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__maj3_1 _0643_ (
    .A(_0121_),
    .B(_0122_),
    .C(_0123_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__xnor2_1 _0644_ (
    .A(_0054_),
    .B(_0055_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0645_ (
    .A(_0126_),
    .SLEEP(_0125_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__nand2_1 _0646_ (
    .A(activation_in[6]),
    .B(weight_in[4]),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__nand2_1 _0647_ (
    .A(activation_in[6]),
    .B(weight_in[3]),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__xor2_1 _0648_ (
    .A(_0064_),
    .B(_0128_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__xnor2_1 _0649_ (
    .A(_0063_),
    .B(_0130_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__xnor2_1 _0650_ (
    .A(_0125_),
    .B(_0126_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__a21oi_1 _0651_ (
    .A1(_0131_),
    .A2(_0132_),
    .B1(_0127_),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__xnor2_1 _0652_ (
    .A(_0069_),
    .B(_0071_),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__xor2_1 _0653_ (
    .A(_0133_),
    .B(_0134_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__maj3_1 _0654_ (
    .A(_0063_),
    .B(_0064_),
    .C(_0128_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__nand2_1 _0655_ (
    .A(_0084_),
    .B(_0136_),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0656_ (
    .A(_0084_),
    .SLEEP(_0136_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__nand2_1 _0657_ (
    .A(_0137_),
    .B(_0138_),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__maj3_1 _0658_ (
    .A(_0133_),
    .B(_0134_),
    .C(_0139_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__xnor2_1 _0659_ (
    .A(_0089_),
    .B(_0090_),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__clkinv_1 _0660_ (
    .A(_0141_),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__xnor2_1 _0661_ (
    .A(_0140_),
    .B(_0141_),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__maj3_1 _0662_ (
    .A(_0138_),
    .B(_0140_),
    .C(_0142_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__xnor2_1 _0663_ (
    .A(_0085_),
    .B(_0103_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__nor2_1 _0664_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__nand2_1 _0665_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__nand2b_1 _0666_ (
    .A_N(_0146_),
    .B(_0147_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__nand2b_1 _0667_ (
    .A_N(activation_in[1]),
    .B(weight_in[7]),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__nand2_1 _0668_ (
    .A(activation_in[2]),
    .B(weight_in[6]),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__nand2_1 _0669_ (
    .A(activation_in[3]),
    .B(weight_in[5]),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__xnor2_1 _0670_ (
    .A(_0149_),
    .B(_0150_),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__maj3_1 _0671_ (
    .A(_0149_),
    .B(_0150_),
    .C(_0151_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__xnor2_1 _0672_ (
    .A(_0123_),
    .B(_0124_),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__nand2_1 _0673_ (
    .A(activation_in[5]),
    .B(weight_in[4]),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__xor2_1 _0674_ (
    .A(_0129_),
    .B(_0155_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__xnor2_1 _0675_ (
    .A(_0063_),
    .B(_0156_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__xor2_1 _0676_ (
    .A(_0153_),
    .B(_0154_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__nand2_1 _0677_ (
    .A(_0157_),
    .B(_0158_),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__o21ai_0 _0678_ (
    .A1(_0153_),
    .A2(_0154_),
    .B1(_0159_),
    .Y(_0160_)
  );
  sky130_fd_sc_hd__xor2_1 _0679_ (
    .A(_0131_),
    .B(_0132_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__maj3_1 _0680_ (
    .A(_0063_),
    .B(_0129_),
    .C(_0155_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__nor2_1 _0681_ (
    .A(_0084_),
    .B(_0162_),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__xnor2_1 _0682_ (
    .A(_0084_),
    .B(_0162_),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__clkinv_1 _0683_ (
    .A(_0164_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__maj3_1 _0684_ (
    .A(_0160_),
    .B(_0161_),
    .C(_0165_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__xnor2_1 _0685_ (
    .A(_0135_),
    .B(_0139_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__maj3_1 _0686_ (
    .A(_0163_),
    .B(_0166_),
    .C(_0167_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__xnor2_1 _0687_ (
    .A(_0138_),
    .B(_0143_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__nand2_1 _0688_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__xnor2_1 _0689_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0171_)
  );
  sky130_fd_sc_hd__nand2b_1 _0690_ (
    .A_N(activation_in[0]),
    .B(weight_in[7]),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__nand2_1 _0691_ (
    .A(activation_in[1]),
    .B(weight_in[6]),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__nand2_1 _0692_ (
    .A(activation_in[2]),
    .B(weight_in[5]),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__maj3_1 _0693_ (
    .A(_0172_),
    .B(_0173_),
    .C(_0174_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__xnor2_1 _0694_ (
    .A(_0151_),
    .B(_0152_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nand2_1 _0695_ (
    .A(activation_in[6]),
    .B(weight_in[2]),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nand2_1 _0696_ (
    .A(activation_in[4]),
    .B(weight_in[3]),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__a22o_1 _0697_ (
    .A1(activation_in[5]),
    .A2(weight_in[3]),
    .B1(weight_in[4]),
    .B2(activation_in[4]),
    .X(_0179_)
  );
  sky130_fd_sc_hd__o21ai_0 _0698_ (
    .A1(_0155_),
    .A2(_0178_),
    .B1(_0179_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__xnor2_1 _0699_ (
    .A(_0177_),
    .B(_0180_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__maj3_1 _0700_ (
    .A(_0175_),
    .B(_0176_),
    .C(_0181_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__clkinv_1 _0701_ (
    .A(_0182_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__xor2_1 _0702_ (
    .A(_0157_),
    .B(_0158_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__nand2_1 _0703_ (
    .A(_0183_),
    .B(_0184_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__o22a_1 _0704_ (
    .A1(_0155_),
    .A2(_0178_),
    .B1(_0180_),
    .B2(_0177_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__nor2_1 _0705_ (
    .A(_0084_),
    .B(_0186_),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__xnor2_1 _0706_ (
    .A(_0084_),
    .B(_0186_),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__nor2_1 _0707_ (
    .A(_0183_),
    .B(_0184_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__xnor2_1 _0708_ (
    .A(_0182_),
    .B(_0184_),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__o21ai_0 _0709_ (
    .A1(_0188_),
    .A2(_0189_),
    .B1(_0185_),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__xnor3_1 _0710_ (
    .A(_0160_),
    .B(_0161_),
    .C(_0164_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__xnor2_1 _0711_ (
    .A(_0191_),
    .B(_0192_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__maj3_1 _0712_ (
    .A(_0187_),
    .B(_0191_),
    .C(_0192_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__xnor3_1 _0713_ (
    .A(_0163_),
    .B(_0166_),
    .C(_0167_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0714_ (
    .A(_0194_),
    .SLEEP(_0195_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__xnor2_1 _0715_ (
    .A(_0194_),
    .B(_0195_),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__nand2_1 _0716_ (
    .A(activation_in[0]),
    .B(weight_in[5]),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__and4_1 _0717_ (
    .A(activation_in[1]),
    .B(activation_in[0]),
    .C(weight_in[5]),
    .D(weight_in[6]),
    .X(_0199_)
  );
  sky130_fd_sc_hd__xnor3_1 _0718_ (
    .A(_0172_),
    .B(_0173_),
    .C(_0174_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__nand2_1 _0719_ (
    .A(activation_in[5]),
    .B(weight_in[2]),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__nand2_1 _0720_ (
    .A(activation_in[3]),
    .B(weight_in[4]),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__nand2_1 _0721_ (
    .A(activation_in[3]),
    .B(weight_in[3]),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__xnor3_1 _0722_ (
    .A(_0178_),
    .B(_0201_),
    .C(_0202_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__maj3_1 _0723_ (
    .A(_0199_),
    .B(_0200_),
    .C(_0204_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__xnor3_1 _0724_ (
    .A(_0175_),
    .B(_0176_),
    .C(_0181_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__nand2_1 _0725_ (
    .A(_0205_),
    .B(_0206_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__and2_0 _0726_ (
    .A(activation_in[6]),
    .B(weight_in[1]),
    .X(_0208_)
  );
  sky130_fd_sc_hd__maj3_1 _0727_ (
    .A(weight_in[7]),
    .B(_0083_),
    .C(_0208_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__a21o_1 _0728_ (
    .A1(weight_in[1]),
    .A2(_0083_),
    .B1(_0084_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__maj3_1 _0729_ (
    .A(_0178_),
    .B(_0201_),
    .C(_0202_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__nor2_1 _0730_ (
    .A(_0210_),
    .B(_0211_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__nand2_1 _0731_ (
    .A(_0210_),
    .B(_0211_),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__nand2b_1 _0732_ (
    .A_N(_0212_),
    .B(_0213_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__xor2_1 _0733_ (
    .A(_0209_),
    .B(_0214_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__xnor2_1 _0734_ (
    .A(_0205_),
    .B(_0206_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__o21ai_0 _0735_ (
    .A1(_0215_),
    .A2(_0216_),
    .B1(_0207_),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__xnor2_1 _0736_ (
    .A(_0188_),
    .B(_0190_),
    .Y(_0218_)
  );
  sky130_fd_sc_hd__and2_0 _0737_ (
    .A(_0217_),
    .B(_0218_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__a21oi_1 _0738_ (
    .A1(_0209_),
    .A2(_0213_),
    .B1(_0212_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__xnor2_1 _0739_ (
    .A(_0217_),
    .B(_0218_),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__nor2_1 _0740_ (
    .A(_0220_),
    .B(_0221_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__xnor2_1 _0741_ (
    .A(_0187_),
    .B(_0193_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__o21ai_0 _0742_ (
    .A1(_0219_),
    .A2(_0222_),
    .B1(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__or3_1 _0743_ (
    .A(_0219_),
    .B(_0222_),
    .C(_0223_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__nand2_1 _0744_ (
    .A(_0224_),
    .B(_0225_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__nand2_1 _0745_ (
    .A(activation_in[4]),
    .B(weight_in[2]),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__nand2_1 _0746_ (
    .A(activation_in[2]),
    .B(weight_in[4]),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__nand2_1 _0747_ (
    .A(activation_in[2]),
    .B(weight_in[3]),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__xnor3_1 _0748_ (
    .A(_0203_),
    .B(_0227_),
    .C(_0228_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__a22oi_1 _0749_ (
    .A1(activation_in[1]),
    .A2(weight_in[5]),
    .B1(weight_in[6]),
    .B2(activation_in[0]),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__nor2_1 _0750_ (
    .A(_0199_),
    .B(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__nand2_1 _0751_ (
    .A(_0230_),
    .B(_0232_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__xor3_1 _0752_ (
    .A(_0199_),
    .B(_0200_),
    .C(_0204_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__nand4_1 _0753_ (
    .A(weight_in[0]),
    .B(activation_in[6]),
    .C(activation_in[5]),
    .D(weight_in[1]),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__maj3_1 _0754_ (
    .A(_0203_),
    .B(_0227_),
    .C(_0228_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__xnor3_1 _0755_ (
    .A(weight_in[7]),
    .B(_0083_),
    .C(_0208_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__xor2_1 _0756_ (
    .A(_0236_),
    .B(_0237_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__xnor2_1 _0757_ (
    .A(_0235_),
    .B(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__xnor2_1 _0758_ (
    .A(_0233_),
    .B(_0234_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__a32o_1 _0759_ (
    .A1(_0230_),
    .A2(_0232_),
    .A3(_0234_),
    .B1(_0239_),
    .B2(_0240_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__xor2_1 _0760_ (
    .A(_0215_),
    .B(_0216_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__maj3_1 _0761_ (
    .A(_0235_),
    .B(_0236_),
    .C(_0237_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__xnor2_1 _0762_ (
    .A(_0241_),
    .B(_0242_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__nor2_1 _0763_ (
    .A(_0243_),
    .B(_0244_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__a21oi_1 _0764_ (
    .A1(_0241_),
    .A2(_0242_),
    .B1(_0245_),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__xor2_1 _0765_ (
    .A(_0220_),
    .B(_0221_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0766_ (
    .A(_0247_),
    .SLEEP(_0246_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__xnor2_1 _0767_ (
    .A(_0246_),
    .B(_0247_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__nand2_1 _0768_ (
    .A(activation_in[3]),
    .B(weight_in[2]),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__nand2_1 _0769_ (
    .A(activation_in[1]),
    .B(weight_in[4]),
    .Y(_0251_)
  );
  sky130_fd_sc_hd__nand2_1 _0770_ (
    .A(activation_in[1]),
    .B(weight_in[3]),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__xnor3_1 _0771_ (
    .A(_0229_),
    .B(_0250_),
    .C(_0251_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__nand3_1 _0772_ (
    .A(activation_in[0]),
    .B(weight_in[5]),
    .C(_0253_),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__xnor2_1 _0773_ (
    .A(_0230_),
    .B(_0232_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__nand4_1 _0774_ (
    .A(weight_in[0]),
    .B(activation_in[5]),
    .C(activation_in[4]),
    .D(weight_in[1]),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__maj3_1 _0775_ (
    .A(_0229_),
    .B(_0250_),
    .C(_0251_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__a22oi_1 _0776_ (
    .A1(weight_in[0]),
    .A2(activation_in[6]),
    .B1(activation_in[5]),
    .B2(weight_in[1]),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0777_ (
    .A(_0235_),
    .SLEEP(_0258_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__clkinv_1 _0778_ (
    .A(_0259_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__xor2_1 _0779_ (
    .A(_0257_),
    .B(_0259_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__xnor2_1 _0780_ (
    .A(_0256_),
    .B(_0261_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__maj3_1 _0781_ (
    .A(_0254_),
    .B(_0255_),
    .C(_0262_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__xnor2_1 _0782_ (
    .A(_0239_),
    .B(_0240_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__nor2_1 _0783_ (
    .A(_0263_),
    .B(_0264_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__maj3_1 _0784_ (
    .A(_0256_),
    .B(_0257_),
    .C(_0260_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__xnor2_1 _0785_ (
    .A(_0263_),
    .B(_0264_),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nor2_1 _0786_ (
    .A(_0266_),
    .B(_0267_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nor2_1 _0787_ (
    .A(_0265_),
    .B(_0268_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__xor2_1 _0788_ (
    .A(_0243_),
    .B(_0244_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__o21ai_0 _0789_ (
    .A1(_0265_),
    .A2(_0268_),
    .B1(_0270_),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__nand4_1 _0790_ (
    .A(weight_in[0]),
    .B(activation_in[4]),
    .C(activation_in[3]),
    .D(weight_in[1]),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__nand2_1 _0791_ (
    .A(activation_in[0]),
    .B(weight_in[4]),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__nand2_1 _0792_ (
    .A(activation_in[2]),
    .B(weight_in[2]),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__xor2_1 _0793_ (
    .A(_0252_),
    .B(_0273_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__maj3_1 _0794_ (
    .A(_0252_),
    .B(_0273_),
    .C(_0274_),
    .X(_0276_)
  );
  sky130_fd_sc_hd__a22o_1 _0795_ (
    .A1(weight_in[0]),
    .A2(activation_in[5]),
    .B1(activation_in[4]),
    .B2(weight_in[1]),
    .X(_0277_)
  );
  sky130_fd_sc_hd__nand2_1 _0796_ (
    .A(_0256_),
    .B(_0277_),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__xor2_1 _0797_ (
    .A(_0276_),
    .B(_0278_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__xnor2_1 _0798_ (
    .A(_0272_),
    .B(_0279_),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__xnor2_1 _0799_ (
    .A(_0198_),
    .B(_0253_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__nand2_1 _0800_ (
    .A(_0280_),
    .B(_0281_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__xor3_1 _0801_ (
    .A(_0254_),
    .B(_0255_),
    .C(_0262_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__maj3_1 _0802_ (
    .A(_0272_),
    .B(_0276_),
    .C(_0278_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__xor2_1 _0803_ (
    .A(_0282_),
    .B(_0283_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__maj3_1 _0804_ (
    .A(_0282_),
    .B(_0283_),
    .C(_0284_),
    .X(_0286_)
  );
  sky130_fd_sc_hd__xor2_1 _0805_ (
    .A(_0266_),
    .B(_0267_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0806_ (
    .A(_0287_),
    .SLEEP(_0286_),
    .X(_0288_)
  );
  sky130_fd_sc_hd__nand2_1 _0807_ (
    .A(weight_in[0]),
    .B(activation_in[2]),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__nand4_1 _0808_ (
    .A(weight_in[0]),
    .B(activation_in[3]),
    .C(activation_in[2]),
    .D(weight_in[1]),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__clkinv_1 _0809_ (
    .A(_0290_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__nand2_1 _0810_ (
    .A(activation_in[0]),
    .B(weight_in[2]),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__nand4_1 _0811_ (
    .A(activation_in[1]),
    .B(activation_in[0]),
    .C(weight_in[2]),
    .D(weight_in[3]),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__a22o_1 _0812_ (
    .A1(weight_in[0]),
    .A2(activation_in[4]),
    .B1(activation_in[3]),
    .B2(weight_in[1]),
    .X(_0294_)
  );
  sky130_fd_sc_hd__and3b_1 _0813_ (
    .A_N(_0293_),
    .B(_0294_),
    .C(_0272_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__a21boi_0 _0814_ (
    .A1(_0272_),
    .A2(_0294_),
    .B1_N(_0293_),
    .Y(_0296_)
  );
  sky130_fd_sc_hd__nor2_1 _0815_ (
    .A(_0295_),
    .B(_0296_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__nor3_1 _0816_ (
    .A(_0290_),
    .B(_0295_),
    .C(_0296_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__o21ai_0 _0817_ (
    .A1(_0295_),
    .A2(_0296_),
    .B1(_0290_),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__xnor2_1 _0818_ (
    .A(_0274_),
    .B(_0275_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__nand3b_1 _0819_ (
    .A_N(_0298_),
    .B(_0299_),
    .C(_0300_),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__xnor3_1 _0820_ (
    .A(_0272_),
    .B(_0279_),
    .C(_0281_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__clkinv_1 _0821_ (
    .A(_0302_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__nor2_1 _0822_ (
    .A(_0295_),
    .B(_0298_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__xnor2_1 _0823_ (
    .A(_0301_),
    .B(_0302_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__maj3_1 _0824_ (
    .A(_0301_),
    .B(_0303_),
    .C(_0304_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__clkinv_1 _0825_ (
    .A(_0306_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__xnor2_1 _0826_ (
    .A(_0284_),
    .B(_0285_),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__xnor3_1 _0827_ (
    .A(_0284_),
    .B(_0285_),
    .C(_0306_),
    .X(_0309_)
  );
  sky130_fd_sc_hd__xnor2_1 _0828_ (
    .A(_0304_),
    .B(_0305_),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__xnor3_1 _0829_ (
    .A(_0290_),
    .B(_0297_),
    .C(_0300_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__nand2_1 _0830_ (
    .A(activation_in[1]),
    .B(weight_in[1]),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__nor2_1 _0831_ (
    .A(_0289_),
    .B(_0312_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__a22oi_1 _0832_ (
    .A1(weight_in[0]),
    .A2(activation_in[3]),
    .B1(activation_in[2]),
    .B2(weight_in[1]),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nor2_1 _0833_ (
    .A(_0291_),
    .B(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__a22oi_1 _0834_ (
    .A1(activation_in[1]),
    .A2(weight_in[2]),
    .B1(weight_in[3]),
    .B2(activation_in[0]),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0835_ (
    .A(_0293_),
    .SLEEP(_0316_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__maj3_1 _0836_ (
    .A(_0313_),
    .B(_0315_),
    .C(_0317_),
    .X(_0318_)
  );
  sky130_fd_sc_hd__xnor2_1 _0837_ (
    .A(_0311_),
    .B(_0318_),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__xor3_1 _0838_ (
    .A(_0313_),
    .B(_0315_),
    .C(_0317_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__nand4_1 _0839_ (
    .A(weight_in[0]),
    .B(activation_in[1]),
    .C(activation_in[0]),
    .D(weight_in[1]),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__xnor2_1 _0840_ (
    .A(_0289_),
    .B(_0312_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__xnor2_1 _0841_ (
    .A(_0321_),
    .B(_0322_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__maj3_1 _0842_ (
    .A(_0292_),
    .B(_0321_),
    .C(_0322_),
    .X(_0324_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0843_ (
    .A(_0320_),
    .SLEEP(_0324_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__maj3_1 _0844_ (
    .A(_0311_),
    .B(_0318_),
    .C(_0325_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__and2_0 _0845_ (
    .A(_0310_),
    .B(_0326_),
    .X(_0327_)
  );
  sky130_fd_sc_hd__maj3_1 _0846_ (
    .A(_0307_),
    .B(_0308_),
    .C(_0327_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__nand2b_1 _0847_ (
    .A_N(_0287_),
    .B(_0286_),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__xor2_1 _0848_ (
    .A(_0286_),
    .B(_0287_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__a21oi_1 _0849_ (
    .A1(_0328_),
    .A2(_0329_),
    .B1(_0288_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__xor2_1 _0850_ (
    .A(_0269_),
    .B(_0270_),
    .X(_0332_)
  );
  sky130_fd_sc_hd__o21ai_0 _0851_ (
    .A1(_0331_),
    .A2(_0332_),
    .B1(_0271_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__a21oi_1 _0852_ (
    .A1(_0249_),
    .A2(_0333_),
    .B1(_0248_),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__o21ai_0 _0853_ (
    .A1(_0226_),
    .A2(_0334_),
    .B1(_0224_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__a21oi_1 _0854_ (
    .A1(_0197_),
    .A2(_0335_),
    .B1(_0196_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__o21ai_0 _0855_ (
    .A1(_0171_),
    .A2(_0336_),
    .B1(_0170_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__a21o_1 _0856_ (
    .A1(_0147_),
    .A2(_0337_),
    .B1(_0146_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__a21oi_1 _0857_ (
    .A1(_0088_),
    .A2(_0114_),
    .B1(_0113_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__xnor2_1 _0858_ (
    .A(_0089_),
    .B(_0111_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__nand2b_1 _0859_ (
    .A_N(_0339_),
    .B(_0340_),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__xnor2_1 _0860_ (
    .A(_0339_),
    .B(_0340_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__nand2_1 _0861_ (
    .A(_0086_),
    .B(_0342_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__a22oi_1 _0862_ (
    .A1(_0086_),
    .A2(_0111_),
    .B1(_0341_),
    .B2(_0343_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__a21oi_1 _0863_ (
    .A1(_0086_),
    .A2(_0117_),
    .B1(_0116_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__xnor2_1 _0864_ (
    .A(_0086_),
    .B(_0342_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__o22ai_1 _0865_ (
    .A1(_0087_),
    .A2(_0111_),
    .B1(_0345_),
    .B2(_0346_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__or3_1 _0866_ (
    .A(_0119_),
    .B(_0344_),
    .C(_0347_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__a21oi_1 _0867_ (
    .A1(_0120_),
    .A2(_0338_),
    .B1(_0348_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__nand2b_1 _0868_ (
    .A_N(psum_in[30]),
    .B(_0349_),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__xor2_1 _0869_ (
    .A(psum_in[30]),
    .B(_0349_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__nor2_1 _0870_ (
    .A(psum_in[29]),
    .B(_0349_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__and2_0 _0871_ (
    .A(psum_in[29]),
    .B(_0349_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__and2_0 _0872_ (
    .A(psum_in[28]),
    .B(_0349_),
    .X(_0354_)
  );
  sky130_fd_sc_hd__xnor2_1 _0873_ (
    .A(psum_in[27]),
    .B(_0349_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__and2_0 _0874_ (
    .A(psum_in[26]),
    .B(_0349_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__xnor2_1 _0875_ (
    .A(psum_in[26]),
    .B(_0349_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0876_ (
    .A(_0355_),
    .SLEEP(_0357_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__xnor2_1 _0877_ (
    .A(psum_in[23]),
    .B(_0349_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__xnor2_1 _0878_ (
    .A(psum_in[22]),
    .B(_0349_),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0879_ (
    .A(_0359_),
    .SLEEP(_0360_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__xnor2_1 _0880_ (
    .A(psum_in[21]),
    .B(_0349_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__nand2_1 _0881_ (
    .A(psum_in[20]),
    .B(_0349_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__xor2_1 _0882_ (
    .A(psum_in[20]),
    .B(_0349_),
    .X(_0364_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0883_ (
    .A(psum_in[19]),
    .SLEEP(_0349_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__nand2_1 _0884_ (
    .A(psum_in[19]),
    .B(_0349_),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__nand2_1 _0885_ (
    .A(psum_in[18]),
    .B(_0349_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__xnor2_1 _0886_ (
    .A(psum_in[18]),
    .B(_0349_),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__and2_0 _0887_ (
    .A(psum_in[17]),
    .B(_0349_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__nor2_1 _0888_ (
    .A(psum_in[17]),
    .B(_0349_),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__and2_0 _0889_ (
    .A(psum_in[16]),
    .B(_0349_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__xor2_1 _0890_ (
    .A(psum_in[15]),
    .B(_0349_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__xor2_1 _0891_ (
    .A(_0120_),
    .B(_0338_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__xnor2_1 _0892_ (
    .A(_0148_),
    .B(_0337_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__xor2_1 _0893_ (
    .A(_0171_),
    .B(_0336_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__xnor2_1 _0894_ (
    .A(psum_in[12]),
    .B(_0375_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__xor2_1 _0895_ (
    .A(_0197_),
    .B(_0335_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__xor2_1 _0896_ (
    .A(_0226_),
    .B(_0334_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__xnor2_1 _0897_ (
    .A(psum_in[10]),
    .B(_0378_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__xor2_1 _0898_ (
    .A(_0249_),
    .B(_0333_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__xor2_1 _0899_ (
    .A(_0331_),
    .B(_0332_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__xnor2_1 _0900_ (
    .A(_0328_),
    .B(_0330_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__xor2_1 _0901_ (
    .A(psum_in[7]),
    .B(_0382_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__xnor2_1 _0902_ (
    .A(_0309_),
    .B(_0327_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__xnor2_1 _0903_ (
    .A(psum_in[6]),
    .B(_0384_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__xor2_1 _0904_ (
    .A(_0310_),
    .B(_0326_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__xnor2_1 _0905_ (
    .A(_0319_),
    .B(_0325_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__xnor2_1 _0906_ (
    .A(_0320_),
    .B(_0324_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__xor2_1 _0907_ (
    .A(_0292_),
    .B(_0323_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__a22o_1 _0908_ (
    .A1(weight_in[0]),
    .A2(activation_in[1]),
    .B1(activation_in[0]),
    .B2(weight_in[1]),
    .X(_0390_)
  );
  sky130_fd_sc_hd__nand3_1 _0909_ (
    .A(psum_in[1]),
    .B(_0321_),
    .C(_0390_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__nand3_1 _0910_ (
    .A(psum_in[0]),
    .B(weight_in[0]),
    .C(activation_in[0]),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__a21o_1 _0911_ (
    .A1(_0321_),
    .A2(_0390_),
    .B1(psum_in[1]),
    .X(_0393_)
  );
  sky130_fd_sc_hd__nand2_1 _0912_ (
    .A(_0391_),
    .B(_0393_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__o21ai_0 _0913_ (
    .A1(_0392_),
    .A2(_0394_),
    .B1(_0391_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__xor2_1 _0914_ (
    .A(psum_in[2]),
    .B(_0389_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__maj3_1 _0915_ (
    .A(psum_in[2]),
    .B(_0389_),
    .C(_0395_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__xor2_1 _0916_ (
    .A(psum_in[3]),
    .B(_0388_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__maj3_1 _0917_ (
    .A(psum_in[3]),
    .B(_0388_),
    .C(_0397_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__xnor2_1 _0918_ (
    .A(psum_in[4]),
    .B(_0387_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__maj3_1 _0919_ (
    .A(psum_in[4]),
    .B(_0387_),
    .C(_0399_),
    .X(_0401_)
  );
  sky130_fd_sc_hd__xor2_1 _0920_ (
    .A(psum_in[5]),
    .B(_0386_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__maj3_1 _0921_ (
    .A(psum_in[5]),
    .B(_0386_),
    .C(_0401_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__maj3_1 _0922_ (
    .A(psum_in[6]),
    .B(_0384_),
    .C(_0403_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__maj3_1 _0923_ (
    .A(psum_in[7]),
    .B(_0382_),
    .C(_0404_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__xor2_1 _0924_ (
    .A(psum_in[8]),
    .B(_0381_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__maj3_1 _0925_ (
    .A(psum_in[8]),
    .B(_0381_),
    .C(_0405_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__xor2_1 _0926_ (
    .A(psum_in[9]),
    .B(_0380_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__maj3_1 _0927_ (
    .A(psum_in[9]),
    .B(_0380_),
    .C(_0407_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__maj3_1 _0928_ (
    .A(psum_in[10]),
    .B(_0378_),
    .C(_0409_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__xor2_1 _0929_ (
    .A(psum_in[11]),
    .B(_0377_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__maj3_1 _0930_ (
    .A(psum_in[11]),
    .B(_0377_),
    .C(_0410_),
    .X(_0412_)
  );
  sky130_fd_sc_hd__maj3_1 _0931_ (
    .A(psum_in[12]),
    .B(_0375_),
    .C(_0412_),
    .X(_0413_)
  );
  sky130_fd_sc_hd__xor2_1 _0932_ (
    .A(psum_in[13]),
    .B(_0374_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__maj3_1 _0933_ (
    .A(psum_in[13]),
    .B(_0374_),
    .C(_0413_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__xor2_1 _0934_ (
    .A(psum_in[14]),
    .B(_0373_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__maj3_1 _0935_ (
    .A(psum_in[14]),
    .B(_0373_),
    .C(_0415_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__maj3_1 _0936_ (
    .A(psum_in[15]),
    .B(_0349_),
    .C(_0417_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__nor2_1 _0937_ (
    .A(psum_in[16]),
    .B(_0349_),
    .Y(_0419_)
  );
  sky130_fd_sc_hd__nor2_1 _0938_ (
    .A(_0371_),
    .B(_0419_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__a21o_1 _0939_ (
    .A1(_0418_),
    .A2(_0420_),
    .B1(_0371_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__a211oi_1 _0940_ (
    .A1(_0418_),
    .A2(_0420_),
    .B1(_0369_),
    .C1(_0371_),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__nor2_1 _0941_ (
    .A(_0370_),
    .B(_0422_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__o31ai_1 _0942_ (
    .A1(_0368_),
    .A2(_0370_),
    .A3(_0422_),
    .B1(_0367_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__o311ai_0 _0943_ (
    .A1(_0368_),
    .A2(_0370_),
    .A3(_0422_),
    .B1(_0367_),
    .C1(_0366_),
    .Y(_0425_)
  );
  sky130_fd_sc_hd__nand3_1 _0944_ (
    .A(_0364_),
    .B(_0365_),
    .C(_0425_),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__o21ai_0 _0945_ (
    .A1(psum_in[21]),
    .A2(psum_in[20]),
    .B1(_0349_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__o41ai_1 _0946_ (
    .A1(psum_in[22]),
    .A2(psum_in[23]),
    .A3(psum_in[21]),
    .A4(psum_in[20]),
    .B1(_0349_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__o31ai_1 _0947_ (
    .A1(_0361_),
    .A2(_0362_),
    .A3(_0426_),
    .B1(_0428_),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__nand2_1 _0948_ (
    .A(psum_in[24]),
    .B(_0349_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__xnor2_1 _0949_ (
    .A(psum_in[24]),
    .B(_0349_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__nand2b_1 _0950_ (
    .A_N(_0431_),
    .B(_0429_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__xnor2_1 _0951_ (
    .A(psum_in[25]),
    .B(_0349_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0952_ (
    .A(_0432_),
    .SLEEP(_0433_),
    .X(_0434_)
  );
  sky130_fd_sc_hd__or4b_1 _0953_ (
    .A(_0358_),
    .B(_0431_),
    .C(_0433_),
    .D_N(_0429_),
    .X(_0435_)
  );
  sky130_fd_sc_hd__o21ai_0 _0954_ (
    .A1(psum_in[25]),
    .A2(psum_in[24]),
    .B1(_0349_),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__o41ai_1 _0955_ (
    .A1(psum_in[26]),
    .A2(psum_in[27]),
    .A3(psum_in[25]),
    .A4(psum_in[24]),
    .B1(_0349_),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__xnor2_1 _0956_ (
    .A(psum_in[28]),
    .B(_0349_),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__a21oi_1 _0957_ (
    .A1(_0435_),
    .A2(_0437_),
    .B1(_0438_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__nor2_1 _0958_ (
    .A(_0354_),
    .B(_0439_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__nor3_1 _0959_ (
    .A(_0353_),
    .B(_0354_),
    .C(_0439_),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__or3_1 _0960_ (
    .A(_0351_),
    .B(_0352_),
    .C(_0441_),
    .X(_0442_)
  );
  sky130_fd_sc_hd__o21ai_0 _0961_ (
    .A1(_0352_),
    .A2(_0441_),
    .B1(_0351_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__o21ai_0 _0962_ (
    .A1(psum_in[30]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__a31oi_1 _0963_ (
    .A1(mac_enable),
    .A2(_0442_),
    .A3(_0443_),
    .B1(_0444_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__a21o_1 _0964_ (
    .A1(psum_out[30]),
    .A2(_0051_),
    .B1(_0445_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__nand2_1 _0965_ (
    .A(psum_out[29]),
    .B(_0051_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__nor2_1 _0966_ (
    .A(_0352_),
    .B(_0353_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__o21ai_0 _0967_ (
    .A1(_0440_),
    .A2(_0447_),
    .B1(mac_enable),
    .Y(_0448_)
  );
  sky130_fd_sc_hd__a21oi_1 _0968_ (
    .A1(_0440_),
    .A2(_0447_),
    .B1(_0448_),
    .Y(_0449_)
  );
  sky130_fd_sc_hd__o21ai_0 _0969_ (
    .A1(psum_in[29]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__o21ai_0 _0970_ (
    .A1(_0449_),
    .A2(_0450_),
    .B1(_0446_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__nand3_1 _0971_ (
    .A(_0435_),
    .B(_0437_),
    .C(_0438_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__nand2b_1 _0972_ (
    .A_N(_0439_),
    .B(_0451_),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__o21ai_0 _0973_ (
    .A1(psum_in[28]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0453_)
  );
  sky130_fd_sc_hd__a21oi_1 _0974_ (
    .A1(mac_enable),
    .A2(_0452_),
    .B1(_0453_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__a21o_1 _0975_ (
    .A1(psum_out[28]),
    .A2(_0051_),
    .B1(_0454_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__nand2_1 _0976_ (
    .A(_0434_),
    .B(_0436_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__a21oi_1 _0977_ (
    .A1(_0434_),
    .A2(_0436_),
    .B1(_0357_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__or3_1 _0978_ (
    .A(_0355_),
    .B(_0356_),
    .C(_0456_),
    .X(_0457_)
  );
  sky130_fd_sc_hd__o21ai_0 _0979_ (
    .A1(_0356_),
    .A2(_0456_),
    .B1(_0355_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__o21ai_0 _0980_ (
    .A1(psum_in[27]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__a31oi_1 _0981_ (
    .A1(mac_enable),
    .A2(_0457_),
    .A3(_0458_),
    .B1(_0459_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__a21o_1 _0982_ (
    .A1(psum_out[27]),
    .A2(_0051_),
    .B1(_0460_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__xor2_1 _0983_ (
    .A(_0357_),
    .B(_0455_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__o21ai_0 _0984_ (
    .A1(psum_in[26]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__a21oi_1 _0985_ (
    .A1(mac_enable),
    .A2(_0461_),
    .B1(_0462_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__a21o_1 _0986_ (
    .A1(psum_out[26]),
    .A2(_0051_),
    .B1(_0463_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__nand2_1 _0987_ (
    .A(psum_out[25]),
    .B(_0051_),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__nand2_1 _0988_ (
    .A(_0430_),
    .B(_0432_),
    .Y(_0465_)
  );
  sky130_fd_sc_hd__xor2_1 _0989_ (
    .A(_0433_),
    .B(_0465_),
    .X(_0466_)
  );
  sky130_fd_sc_hd__a21oi_1 _0990_ (
    .A1(mac_enable),
    .A2(_0466_),
    .B1(_0051_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__o21ai_0 _0991_ (
    .A1(psum_in[25]),
    .A2(mac_enable),
    .B1(_0467_),
    .Y(_0468_)
  );
  sky130_fd_sc_hd__nand2_1 _0992_ (
    .A(_0464_),
    .B(_0468_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__xor2_1 _0993_ (
    .A(_0429_),
    .B(_0431_),
    .X(_0469_)
  );
  sky130_fd_sc_hd__o21ai_0 _0994_ (
    .A1(psum_in[24]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__a21oi_1 _0995_ (
    .A1(mac_enable),
    .A2(_0469_),
    .B1(_0470_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__a21o_1 _0996_ (
    .A1(psum_out[24]),
    .A2(_0051_),
    .B1(_0471_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__nand2_1 _0997_ (
    .A(psum_out[23]),
    .B(_0051_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__o21ai_0 _0998_ (
    .A1(_0362_),
    .A2(_0426_),
    .B1(_0427_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__maj3_1 _0999_ (
    .A(psum_in[22]),
    .B(_0349_),
    .C(_0473_),
    .X(_0474_)
  );
  sky130_fd_sc_hd__xor2_1 _1000_ (
    .A(_0359_),
    .B(_0474_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__a21oi_1 _1001_ (
    .A1(mac_enable),
    .A2(_0475_),
    .B1(_0051_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__o21ai_0 _1002_ (
    .A1(psum_in[23]),
    .A2(mac_enable),
    .B1(_0476_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__nand2_1 _1003_ (
    .A(_0472_),
    .B(_0477_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__xor2_1 _1004_ (
    .A(_0360_),
    .B(_0473_),
    .X(_0478_)
  );
  sky130_fd_sc_hd__o21ai_0 _1005_ (
    .A1(psum_in[22]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__a21oi_1 _1006_ (
    .A1(mac_enable),
    .A2(_0478_),
    .B1(_0479_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__a21o_1 _1007_ (
    .A1(psum_out[22]),
    .A2(_0051_),
    .B1(_0480_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__nand2_1 _1008_ (
    .A(psum_out[21]),
    .B(_0051_),
    .Y(_0481_)
  );
  sky130_fd_sc_hd__nand2_1 _1009_ (
    .A(_0363_),
    .B(_0426_),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__xor2_1 _1010_ (
    .A(_0362_),
    .B(_0482_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__a21oi_1 _1011_ (
    .A1(mac_enable),
    .A2(_0483_),
    .B1(_0051_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__o21ai_0 _1012_ (
    .A1(psum_in[21]),
    .A2(mac_enable),
    .B1(_0484_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__nand2_1 _1013_ (
    .A(_0481_),
    .B(_0485_),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__nand2_1 _1014_ (
    .A(psum_out[20]),
    .B(_0051_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__a21oi_1 _1015_ (
    .A1(_0365_),
    .A2(_0425_),
    .B1(_0364_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1016_ (
    .A(_0426_),
    .SLEEP(_0487_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1017_ (
    .A(mac_enable),
    .SLEEP(_0488_),
    .X(_0489_)
  );
  sky130_fd_sc_hd__o21ai_0 _1018_ (
    .A1(psum_in[20]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__o21ai_0 _1019_ (
    .A1(_0489_),
    .A2(_0490_),
    .B1(_0486_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__nand2_1 _1020_ (
    .A(psum_out[19]),
    .B(_0051_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__nand2_1 _1021_ (
    .A(_0365_),
    .B(_0366_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__o21ai_0 _1022_ (
    .A1(_0424_),
    .A2(_0492_),
    .B1(mac_enable),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__a21oi_1 _1023_ (
    .A1(_0424_),
    .A2(_0492_),
    .B1(_0493_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__o21ai_0 _1024_ (
    .A1(psum_in[19]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__o21ai_0 _1025_ (
    .A1(_0494_),
    .A2(_0495_),
    .B1(_0491_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__xor2_1 _1026_ (
    .A(_0368_),
    .B(_0423_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__o21ai_0 _1027_ (
    .A1(psum_in[18]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__a21oi_1 _1028_ (
    .A1(mac_enable),
    .A2(_0496_),
    .B1(_0497_),
    .Y(_0498_)
  );
  sky130_fd_sc_hd__a21o_1 _1029_ (
    .A1(psum_out[18]),
    .A2(_0051_),
    .B1(_0498_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__nand2_1 _1030_ (
    .A(psum_out[17]),
    .B(_0051_),
    .Y(_0499_)
  );
  sky130_fd_sc_hd__nor2_1 _1031_ (
    .A(_0369_),
    .B(_0370_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__xnor2_1 _1032_ (
    .A(_0421_),
    .B(_0500_),
    .Y(_0501_)
  );
  sky130_fd_sc_hd__a21oi_1 _1033_ (
    .A1(mac_enable),
    .A2(_0501_),
    .B1(_0051_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__o21ai_0 _1034_ (
    .A1(psum_in[17]),
    .A2(mac_enable),
    .B1(_0502_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__nand2_1 _1035_ (
    .A(_0499_),
    .B(_0503_),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__xnor2_1 _1036_ (
    .A(_0418_),
    .B(_0420_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__o21ai_0 _1037_ (
    .A1(psum_in[16]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__a21oi_1 _1038_ (
    .A1(mac_enable),
    .A2(_0504_),
    .B1(_0505_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__a21o_1 _1039_ (
    .A1(psum_out[16]),
    .A2(_0051_),
    .B1(_0506_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__xnor2_1 _1040_ (
    .A(_0372_),
    .B(_0417_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__o21ai_0 _1041_ (
    .A1(psum_in[15]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__a21oi_1 _1042_ (
    .A1(mac_enable),
    .A2(_0507_),
    .B1(_0508_),
    .Y(_0509_)
  );
  sky130_fd_sc_hd__a21o_1 _1043_ (
    .A1(psum_out[15]),
    .A2(_0051_),
    .B1(_0509_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__xnor2_1 _1044_ (
    .A(_0415_),
    .B(_0416_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__o21ai_0 _1045_ (
    .A1(psum_in[14]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__a21oi_1 _1046_ (
    .A1(mac_enable),
    .A2(_0510_),
    .B1(_0511_),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__a21o_1 _1047_ (
    .A1(psum_out[14]),
    .A2(_0051_),
    .B1(_0512_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__xnor2_1 _1048_ (
    .A(_0413_),
    .B(_0414_),
    .Y(_0513_)
  );
  sky130_fd_sc_hd__o21ai_0 _1049_ (
    .A1(psum_in[13]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__a21oi_1 _1050_ (
    .A1(mac_enable),
    .A2(_0513_),
    .B1(_0514_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a21o_1 _1051_ (
    .A1(psum_out[13]),
    .A2(_0051_),
    .B1(_0515_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__xor2_1 _1052_ (
    .A(_0376_),
    .B(_0412_),
    .X(_0516_)
  );
  sky130_fd_sc_hd__o21ai_0 _1053_ (
    .A1(psum_in[12]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__a21oi_1 _1054_ (
    .A1(mac_enable),
    .A2(_0516_),
    .B1(_0517_),
    .Y(_0518_)
  );
  sky130_fd_sc_hd__a21o_1 _1055_ (
    .A1(psum_out[12]),
    .A2(_0051_),
    .B1(_0518_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__xnor2_1 _1056_ (
    .A(_0410_),
    .B(_0411_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__o21ai_0 _1057_ (
    .A1(psum_in[11]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__a21oi_1 _1058_ (
    .A1(mac_enable),
    .A2(_0519_),
    .B1(_0520_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__a21o_1 _1059_ (
    .A1(psum_out[11]),
    .A2(_0051_),
    .B1(_0521_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__xor2_1 _1060_ (
    .A(_0379_),
    .B(_0409_),
    .X(_0522_)
  );
  sky130_fd_sc_hd__o21ai_0 _1061_ (
    .A1(psum_in[10]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__a21oi_1 _1062_ (
    .A1(mac_enable),
    .A2(_0522_),
    .B1(_0523_),
    .Y(_0524_)
  );
  sky130_fd_sc_hd__a21o_1 _1063_ (
    .A1(psum_out[10]),
    .A2(_0051_),
    .B1(_0524_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__xnor2_1 _1064_ (
    .A(_0407_),
    .B(_0408_),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__o21ai_0 _1065_ (
    .A1(psum_in[9]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0526_)
  );
  sky130_fd_sc_hd__a21oi_1 _1066_ (
    .A1(mac_enable),
    .A2(_0525_),
    .B1(_0526_),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__a21o_1 _1067_ (
    .A1(psum_out[9]),
    .A2(_0051_),
    .B1(_0527_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__xnor2_1 _1068_ (
    .A(_0405_),
    .B(_0406_),
    .Y(_0528_)
  );
  sky130_fd_sc_hd__o21ai_0 _1069_ (
    .A1(psum_in[8]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0529_)
  );
  sky130_fd_sc_hd__a21oi_1 _1070_ (
    .A1(mac_enable),
    .A2(_0528_),
    .B1(_0529_),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__a21o_1 _1071_ (
    .A1(psum_out[8]),
    .A2(_0051_),
    .B1(_0530_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__xnor2_1 _1072_ (
    .A(_0383_),
    .B(_0404_),
    .Y(_0531_)
  );
  sky130_fd_sc_hd__o21ai_0 _1073_ (
    .A1(psum_in[7]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__a21oi_1 _1074_ (
    .A1(mac_enable),
    .A2(_0531_),
    .B1(_0532_),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__a21o_1 _1075_ (
    .A1(psum_out[7]),
    .A2(_0051_),
    .B1(_0533_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__xor2_1 _1076_ (
    .A(_0385_),
    .B(_0403_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__o21ai_0 _1077_ (
    .A1(psum_in[6]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__a21oi_1 _1078_ (
    .A1(mac_enable),
    .A2(_0534_),
    .B1(_0535_),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__a21o_1 _1079_ (
    .A1(psum_out[6]),
    .A2(_0051_),
    .B1(_0536_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__xnor2_1 _1080_ (
    .A(_0401_),
    .B(_0402_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__o21ai_0 _1081_ (
    .A1(psum_in[5]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0538_)
  );
  sky130_fd_sc_hd__a21oi_1 _1082_ (
    .A1(mac_enable),
    .A2(_0537_),
    .B1(_0538_),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__a21o_1 _1083_ (
    .A1(psum_out[5]),
    .A2(_0051_),
    .B1(_0539_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__xor2_1 _1084_ (
    .A(_0399_),
    .B(_0400_),
    .X(_0540_)
  );
  sky130_fd_sc_hd__o21ai_0 _1085_ (
    .A1(psum_in[4]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0541_)
  );
  sky130_fd_sc_hd__a21oi_1 _1086_ (
    .A1(mac_enable),
    .A2(_0540_),
    .B1(_0541_),
    .Y(_0542_)
  );
  sky130_fd_sc_hd__a21o_1 _1087_ (
    .A1(psum_out[4]),
    .A2(_0051_),
    .B1(_0542_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__xnor2_1 _1088_ (
    .A(_0397_),
    .B(_0398_),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__o21ai_0 _1089_ (
    .A1(psum_in[3]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__a21oi_1 _1090_ (
    .A1(mac_enable),
    .A2(_0543_),
    .B1(_0544_),
    .Y(_0545_)
  );
  sky130_fd_sc_hd__a21o_1 _1091_ (
    .A1(psum_out[3]),
    .A2(_0051_),
    .B1(_0545_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__xnor2_1 _1092_ (
    .A(_0395_),
    .B(_0396_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__o21ai_0 _1093_ (
    .A1(psum_in[2]),
    .A2(mac_enable),
    .B1(_0050_),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__a21oi_1 _1094_ (
    .A1(mac_enable),
    .A2(_0546_),
    .B1(_0547_),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__a21o_1 _1095_ (
    .A1(psum_out[2]),
    .A2(_0051_),
    .B1(_0548_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__xor2_1 _1096_ (
    .A(_0392_),
    .B(_0394_),
    .X(_0549_)
  );
  sky130_fd_sc_hd__mux2i_1 _1097_ (
    .A0(psum_in[1]),
    .A1(_0549_),
    .S(mac_enable),
    .Y(_0550_)
  );
  sky130_fd_sc_hd__nand2_1 _1098_ (
    .A(psum_out[1]),
    .B(_0051_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__o21ai_0 _1099_ (
    .A1(_0051_),
    .A2(_0550_),
    .B1(_0551_),
    .Y(_0036_)
  );
  sky130_fd_sc_hd__nor2_1 _1100_ (
    .A(psum_out[0]),
    .B(_0050_),
    .Y(_0552_)
  );
  sky130_fd_sc_hd__nand3_1 _1101_ (
    .A(weight_in[0]),
    .B(activation_in[0]),
    .C(mac_enable),
    .Y(_0553_)
  );
  sky130_fd_sc_hd__xor2_1 _1102_ (
    .A(psum_in[0]),
    .B(_0553_),
    .X(_0554_)
  );
  sky130_fd_sc_hd__a21oi_1 _1103_ (
    .A1(_0050_),
    .A2(_0554_),
    .B1(_0552_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__mux2_1 _1104_ (
    .A0(activation_out[6]),
    .A1(activation_in[6]),
    .S(pe_enable),
    .X(_0038_)
  );
  sky130_fd_sc_hd__mux2_1 _1105_ (
    .A0(activation_out[5]),
    .A1(activation_in[5]),
    .S(pe_enable),
    .X(_0039_)
  );
  sky130_fd_sc_hd__mux2_1 _1106_ (
    .A0(activation_out[4]),
    .A1(activation_in[4]),
    .S(pe_enable),
    .X(_0040_)
  );
  sky130_fd_sc_hd__mux2_1 _1107_ (
    .A0(activation_out[3]),
    .A1(activation_in[3]),
    .S(pe_enable),
    .X(_0041_)
  );
  sky130_fd_sc_hd__mux2_1 _1108_ (
    .A0(activation_out[2]),
    .A1(activation_in[2]),
    .S(pe_enable),
    .X(_0042_)
  );
  sky130_fd_sc_hd__mux2_1 _1109_ (
    .A0(activation_out[1]),
    .A1(activation_in[1]),
    .S(pe_enable),
    .X(_0043_)
  );
  sky130_fd_sc_hd__mux2_1 _1110_ (
    .A0(activation_out[0]),
    .A1(activation_in[0]),
    .S(pe_enable),
    .X(_0044_)
  );
  sky130_fd_sc_hd__o21ai_0 _1111_ (
    .A1(pe_enable),
    .A2(_0049_),
    .B1(_0051_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__mux2_1 _1112_ (
    .A0(weight_out[7]),
    .A1(weight_in[7]),
    .S(pe_enable),
    .X(_0046_)
  );
  sky130_fd_sc_hd__mux2_1 _1113_ (
    .A0(activation_out[7]),
    .A1(activation_in[7]),
    .S(pe_enable),
    .X(_0047_)
  );
  sky130_fd_sc_hd__nor2_1 _1114_ (
    .A(psum_out[31]),
    .B(_0050_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__and4b_1 _1115_ (
    .A_N(_0349_),
    .B(_0439_),
    .C(psum_in[29]),
    .D(psum_in[30]),
    .X(_0556_)
  );
  sky130_fd_sc_hd__nor4_1 _1116_ (
    .A(_0350_),
    .B(_0353_),
    .C(_0354_),
    .D(_0439_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__o21ai_0 _1117_ (
    .A1(_0556_),
    .A2(_0557_),
    .B1(mac_enable),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__xor2_1 _1118_ (
    .A(psum_in[31]),
    .B(_0558_),
    .X(_0559_)
  );
  sky130_fd_sc_hd__a21oi_1 _1119_ (
    .A1(_0050_),
    .A2(_0559_),
    .B1(_0555_),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1120_ (
    .CLK(clk),
    .D(_0045_),
    .Q(valid_out),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1121_ (
    .CLK(clk),
    .D(_0044_),
    .Q(activation_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1122_ (
    .CLK(clk),
    .D(_0043_),
    .Q(activation_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1123_ (
    .CLK(clk),
    .D(_0042_),
    .Q(activation_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1124_ (
    .CLK(clk),
    .D(_0041_),
    .Q(activation_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1125_ (
    .CLK(clk),
    .D(_0040_),
    .Q(activation_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1126_ (
    .CLK(clk),
    .D(_0039_),
    .Q(activation_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1127_ (
    .CLK(clk),
    .D(_0038_),
    .Q(activation_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1128_ (
    .CLK(clk),
    .D(_0047_),
    .Q(activation_out[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1129_ (
    .CLK(clk),
    .D(_0037_),
    .Q(psum_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1130_ (
    .CLK(clk),
    .D(_0036_),
    .Q(psum_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1131_ (
    .CLK(clk),
    .D(_0035_),
    .Q(psum_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1132_ (
    .CLK(clk),
    .D(_0034_),
    .Q(psum_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1133_ (
    .CLK(clk),
    .D(_0033_),
    .Q(psum_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1134_ (
    .CLK(clk),
    .D(_0032_),
    .Q(psum_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1135_ (
    .CLK(clk),
    .D(_0031_),
    .Q(psum_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1136_ (
    .CLK(clk),
    .D(_0030_),
    .Q(psum_out[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1137_ (
    .CLK(clk),
    .D(_0029_),
    .Q(psum_out[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1138_ (
    .CLK(clk),
    .D(_0028_),
    .Q(psum_out[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1139_ (
    .CLK(clk),
    .D(_0027_),
    .Q(psum_out[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1140_ (
    .CLK(clk),
    .D(_0026_),
    .Q(psum_out[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1141_ (
    .CLK(clk),
    .D(_0025_),
    .Q(psum_out[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1142_ (
    .CLK(clk),
    .D(_0024_),
    .Q(psum_out[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1143_ (
    .CLK(clk),
    .D(_0023_),
    .Q(psum_out[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1144_ (
    .CLK(clk),
    .D(_0022_),
    .Q(psum_out[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1145_ (
    .CLK(clk),
    .D(_0021_),
    .Q(psum_out[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1146_ (
    .CLK(clk),
    .D(_0020_),
    .Q(psum_out[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1147_ (
    .CLK(clk),
    .D(_0019_),
    .Q(psum_out[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1148_ (
    .CLK(clk),
    .D(_0018_),
    .Q(psum_out[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1149_ (
    .CLK(clk),
    .D(_0017_),
    .Q(psum_out[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1150_ (
    .CLK(clk),
    .D(_0016_),
    .Q(psum_out[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1151_ (
    .CLK(clk),
    .D(_0015_),
    .Q(psum_out[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1152_ (
    .CLK(clk),
    .D(_0014_),
    .Q(psum_out[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1153_ (
    .CLK(clk),
    .D(_0013_),
    .Q(psum_out[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1154_ (
    .CLK(clk),
    .D(_0012_),
    .Q(psum_out[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1155_ (
    .CLK(clk),
    .D(_0011_),
    .Q(psum_out[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1156_ (
    .CLK(clk),
    .D(_0010_),
    .Q(psum_out[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1157_ (
    .CLK(clk),
    .D(_0009_),
    .Q(psum_out[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1158_ (
    .CLK(clk),
    .D(_0008_),
    .Q(psum_out[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1159_ (
    .CLK(clk),
    .D(_0007_),
    .Q(psum_out[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1160_ (
    .CLK(clk),
    .D(_0048_),
    .Q(psum_out[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1161_ (
    .CLK(clk),
    .D(_0006_),
    .Q(weight_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1162_ (
    .CLK(clk),
    .D(_0005_),
    .Q(weight_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1163_ (
    .CLK(clk),
    .D(_0004_),
    .Q(weight_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1164_ (
    .CLK(clk),
    .D(_0003_),
    .Q(weight_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1165_ (
    .CLK(clk),
    .D(_0002_),
    .Q(weight_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1166_ (
    .CLK(clk),
    .D(_0001_),
    .Q(weight_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1167_ (
    .CLK(clk),
    .D(_0000_),
    .Q(weight_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1168_ (
    .CLK(clk),
    .D(_0046_),
    .Q(weight_out[7]),
    .RESET_B(rst_n)
  );
  \$paramod\operand_gating\DATA_WIDTH=s32'00000000000000000000000000001000  u_operand_gating (
    .activation(activation_in),
    .mac_enable(mac_enable),
    .weight(weight_in)
  );
endmodule
